// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/brands/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/brands/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/brands/[id].put').default>>>>
    }
    '/api/brands': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/brands/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/brands/index.post').default>>>>
    }
    '/api/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].put').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.post').default>>>>
    }
    '/api/divisions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/[id].put').default>>>>
    }
    '/api/divisions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/divisions/index.post').default>>>>
    }
    '/api/floors/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/floors/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/floors/[id].put').default>>>>
    }
    '/api/floors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/floors/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/floors/index.post').default>>>>
    }
    '/api/inventories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventories/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventories/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventories/[id].put').default>>>>
    }
    '/api/inventories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventories/index.post').default>>>>
    }
    '/api/inventories/table': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventories/table.get').default>>>>
    }
    '/api/inventory-items/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory-items/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory-items/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory-items/[id].put').default>>>>
    }
    '/api/inventory-items/datatable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory-items/datatable.get').default>>>>
    }
    '/api/inventory-items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory-items/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory-items/index.post').default>>>>
    }
    '/api/item-types/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/item-types/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/item-types/[id].put').default>>>>
    }
    '/api/item-types': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/item-types/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/item-types/index.post').default>>>>
    }
    '/api/rooms/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id].put').default>>>>
    }
    '/api/rooms': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/index.post').default>>>>
    }
    '/api/units/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/units/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/units/[id].put').default>>>>
    }
    '/api/units': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/units/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/units/index.post').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].put').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/api/users/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}