// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/3/2025, 11:18:17 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/macbookpro/Documents/inventarisNextjs/web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/plugins/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/inventarisNextjs/web/app/composables/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/inventarisNextjs/web/app/utils/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/inventarisNextjs/web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/inventarisNextjs/web/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;